In [72]:
from sklearn.metrics import accuracy_score, roc_auc_score, roc_curve
import pandas as pd
import numpy as np

In [87]:
prediction = pd.read_csv('submitted/predict_target_1_lstm_with_gru_0929_1.csv')

In [88]:
prediction.head()

Unnamed: 0    result  target
0        ADA  0.393166     0.0
1        BAT  0.487779     0.0
2        BNB  0.518176     0.0
3        BTC  0.404871     0.0
4        BTT  0.464437     0.0

In [89]:
result = 1 - prediction['result'].values
target = prediction['target'].values

In [90]:
result

array([0.60683441, 0.51222143, 0.48182392, 0.5951294 , 0.53556305,
       0.60833189, 0.49783808, 0.50073028, 0.52019674, 0.50523639,
       0.5151884 , 0.45903116, 0.56276378, 0.4960745 , 0.56306311,
       0.61341289, 0.62114662, 0.51864779, 0.50822294, 0.4665029 ,
       0.52439079, 0.46604133])

In [91]:
target

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.])

In [92]:
roc_auc_score(target, result)

ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.

In [82]:
target

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 0., 1.])

In [9]:
result

array([0.40957987, 0.49841005, 0.52570122, 0.46632996, 0.46434939,
       0.3722254 , 0.494349  , 0.49454051, 0.50831836, 0.50798106,
       0.51131612, 0.52074951, 0.4808324 , 0.48875239, 0.48548231,
       0.41113985, 0.44138095, 0.51356953, 0.49835789, 0.48298639,
       0.41563708, 0.46561503])

In [10]:
roc_curve(target, result, drop_intermediate=False)

(array([0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1. , 1. , 1. , 1. ]),
 array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
        0.5 , 0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.85, 0.9 , 0.95,
        1.  ]),
 array([1.52570122, 0.52570122, 0.52074951, 0.51356953, 0.51131612,
        0.50831836, 0.50798106, 0.49841005, 0.49835789, 0.49454051,
        0.494349  , 0.48875239, 0.48548231, 0.48298639, 0.4808324 ,
        0.46632996, 0.46561503, 0.46434939, 0.44138095, 0.41563708,
        0.41113985, 0.40957987, 0.3722254 ]))

In [103]:
prediction2 = pd.read_csv('submitted/predict_target_2_lstm_with_gru_0929_2.csv')

In [104]:
prediction2.head()

Unnamed: 0    result    target
0        ADA  1.034937  0.965111
1        BAT  0.994188  0.952344
2        BNB  1.023774  0.975291
3        BTC  0.928056  0.976517
4        BTT  0.988739  0.972371

In [105]:
result = prediction2['result'].values
target = prediction2['target'].values

In [106]:
def mape(y_true, y_pred):
    epsilon = np.finfo(np.float64).eps
    mape = np.abs(y_pred - y_true) / np.maximum(np.abs(y_true), epsilon)
    output_errors = np.average(mape, axis=0)
    return output_errors

In [107]:
mape(np.array(target), np.array(result))

0.05007449501144649

In [102]:
mape(np.array(target), np.array(result))

0.05007449501144649

In [66]:
target

array([1.13645518, 1.13081491, 1.10046458, 1.0689646 , 1.11815286,
       1.31583369, 1.11499369, 1.10653627, 1.11896968, 1.11244798,
       1.12593603, 1.1414566 , 1.08686864, 1.17478514, 1.14510536,
       1.12943995, 1.1549598 , 1.1189667 , 1.10041368, 1.12431192,
       1.14754665, 1.08594453])

In [18]:
f = open('parameters.txt', 'r', encoding='UTF-8')
data = f.read()
f.close()

In [19]:
data.split('[')[-1].split(']')[0]

"'ohlc_Binance_ADAUSDT_d.csv', {'hidden_dim_lstm_1': 40.0, 'hidden_dim_lstm_2': 100.0, 'hidden_dim_gru': 80.0, 'dropout': 0.26208630215377515, 'optimizer': 'Adam', 'weight_decay': 0.00011567327199145979, 'adam_lr': 0.002537815508265664, 'batch_size': 96.0, 'windows': 1.0}"

In [21]:
param = pd.read_csv('parameter.csv')

In [47]:
param_dict = param[param['file_name'] == 'ohlc_Binance_ADAUSDT_d.csv']['best_parameter'].values[0]

In [48]:
import ast

In [49]:
ast.literal_eval(param_dict)

{'hidden_dim_lstm_1': 20.0,
 'hidden_dim_lstm_2': 30.0,
 'hidden_dim_gru': 70.0,
 'dropout': 0.1335544922106665,
 'optimizer': 'MomentumSGD',
 'weight_decay': 5.381997243445295e-06,
 'momentum_sgd_lr': 0.03441810015213391,
 'batch_size': 128.0,
 'windows': 3.0}

In [45]:
param.head()

file_name  \
0  ohlc_Binance_ADAUSDT_d.csv   
1  ohlc_Binance_BATUSDT_d.csv   
2  ohlc_Binance_BNBUSDT_d.csv   
3  ohlc_Binance_BTCUSDT_d.csv   
4  ohlc_Binance_BTTUSDT_d.csv   

                                      best_parameter  
0  {'hidden_dim_lstm_1': 20.0, 'hidden_dim_lstm_2...  
1  {'hidden_dim_lstm_1': 70.0, 'hidden_dim_lstm_2...  
2  {'hidden_dim_lstm_1': 50.0, 'hidden_dim_lstm_2...  
3  {'hidden_dim_lstm_1': 90.0, 'hidden_dim_lstm_2...  
4  {'hidden_dim_lstm_1': 30.0, 'hidden_dim_lstm_2...